# Generated by Django 3.0.3 on 2020-02-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('lastname', models.CharField(max_length=20, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('diagnos', models.TextField(verbose_name='Диагноз')),
                ('photo', models.ImageField(upload_to='main_photo/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('money', models.PositiveSmallIntegerField(verbose_name='Необходимая сумма')),
                ('pay_date', models.DateField(verbose_name='Дата оплаты')),
                ('pay_description', models.TextField(help_text='Иванову С. было оплачено лечение', verbose_name='Описание оплаты')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО в дательном падеже')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soffund.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Дети',
            },
        ),
        migrations.CreateModel(
            name='FundDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование документа фонда')),
                ('description', models.TextField(verbose_name='Описание документа фонда')),
                ('document_image', models.FileField(upload_to='document_image/fund/', verbose_name='Файл для скачивания')),
            ],
            options={
                'verbose_name': 'Документ для скачивания',
                'verbose_name_plural': 'Документы для скачивания',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_image', models.ImageField(upload_to='document_image/children/', verbose_name='Сканы документов')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soffund.Child', verbose_name='Документы ребенка')),
            ],
            options={
                'verbose_name': 'Документы ребенка',
                'verbose_name_plural': 'Документы детей',
            },
        ),
    ]
