# Generated by Django 3.0.3 on 2020-02-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soffund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='pay_date',
            field=models.DateField(blank=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='child',
            name='pay_description',
            field=models.TextField(blank=True, help_text='Иванову С. было оплачено лечение', verbose_name='Описание оплаты'),
        ),
    ]
