# Generated by Django 3.0.3 on 2020-02-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soffund', '0002_auto_20200222_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='pay_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='child',
            name='pay_description',
            field=models.TextField(blank=True, help_text='Иванову С. было оплачено лечение', null=True, verbose_name='Описание оплаты'),
        ),
    ]
